Ported improved stack traces from monix
monix/monix-bio pull request #190
Opened 2020-10-31 19:19 UTC by WesselVS

Thanks for this library! I am really excited about the stack traces functionality in monix, so I decided to help a little bit with getting this into bio. It's based on https://github.com/monix/monix/pull/1267/. Couple of things:

* In `TaskRunLoop`, `augmentException` is only used on throwable types. I used `isInstanceOf` checks to guard this.
* The tracing unit tests do not produce equivalent results between monix and monix-bio. It seems that 'runToFuture' traces differ in numbers. This smells like a bug somewhere, but the traces still seem reasonable.

2020-11-07 10:48 UTC, Avasil requested changes
Thank you so much!
You are saving me a lot of work. :) 

> The tracing unit tests do not produce equivalent results between monix and monix-bio. It seems that 'runToFuture' traces differ in numbers. This smells like a bug somewhere, but the traces still seem reasonable.

I will play with the changes after merging this PR and before releasing but it's probably not a blocker

> I copied RingBuffer, this needs to be removed when the new monix release is available.

I'm going through the release process right now but I'm doing it through GitHub Actions for the first time so it will probably take a few tries before it works properly 😅

2020-11-07 10:48 UTC, Avasil commented on build.sbt
> +      "-Dmonix.bio.tracing=true",
There's no such option, I blindly copied it from Cats-Effect, will have to correct it. Maybe it should be enhancedExceptions to not rely on the default value?

2020-11-07 10:48 UTC, Avasil commented on core/jvm/src/main/scala/monix/bio/internal/TaskRunSyncUnsafe.scala
> +          if (isStackTracing && enhancedExceptions) {
We should add it to `case Termination` too

2020-11-07 10:48 UTC, Avasil commented on core/jvm/src/main/scala/monix/bio/internal/TaskRunSyncUnsafe.scala
> +            if (error.isInstanceOf[Throwable]) {
`E` is always `Throwable` in `runSyncUnsafe` so we could get rid of this check

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/IO.scala
> +  def raiseError[E](ex: E): IO[E, Nothing] = {
I think we should also do a similar thing for `Termination`

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/IO.scala
> +  def suspend[A](fa: => Task[A]): Task[A] = {
I think we should also do a similar thing for `SuspendTotal`

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/IO.scala
> +  def eval[A](a: => A): Task[A] = {
We should also do a similar thing for `EvalTotal`

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/Task.scala
> +  val trace: UIO[TaskTrace] = IO.trace
We return `Task` on this alias, as a convention

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/internal/TaskRunLoop.scala
>  private[bio] object TaskRunLoop {
we have to augment exceptions in `Termination` case as well

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/internal/TaskTracing.scala
> +private[bio] object TaskTracing {
I would rename it to `IOTracing`, I plan to gradually change `Task` names in internal classes

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/tracing/TaskEvent.scala
> +sealed abstract class TaskEvent
This one is public so it should be definitely `IOEvent`

2020-11-07 10:48 UTC, Avasil commented on core/shared/src/main/scala/monix/bio/tracing/TaskTrace.scala
> +final case class TaskTrace(events: List[TaskEvent], captured: Int, omitted: Int) {
`IOTrace`

2020-11-07 10:48 UTC, Avasil commented on tracingTests/src/fulltracing/scala/tracing/FullStackTracingSuite.scala
> +object FullStackTracingSuite extends BaseTestSuite {
Once we add traces in evalTotal / suspendTotal / terminate then it would be good to add some tests for them

2020-11-07 12:33 UTC, paualarco commented on core/shared/src/main/scala/monix/bio/IO.scala
> +    }
this if-else conditions repeat over different operators, wouldn't be good idea to encapsulate it in a function `getTrace`? or even better, in a variable, so it does not need to be evaluated every time?

2020-11-08 08:18 UTC, WesselVS commented on build.sbt
> +      "-Dmonix.bio.tracing=true",
Changed to enhancedExceptions

2020-11-08 08:18 UTC, WesselVS commented on core/jvm/src/main/scala/monix/bio/internal/TaskRunSyncUnsafe.scala
> +          if (isStackTracing && enhancedExceptions) {
Done

2020-11-08 08:18 UTC, WesselVS commented on core/jvm/src/main/scala/monix/bio/internal/TaskRunSyncUnsafe.scala
> +            if (error.isInstanceOf[Throwable]) {
If I remove the check, unit tests fail with cast exceptions.

2020-11-08 08:18 UTC, WesselVS commented on core/shared/src/main/scala/monix/bio/IO.scala
> +  def raiseError[E](ex: E): IO[E, Nothing] = {
Done

2020-11-08 08:19 UTC, WesselVS commented on core/shared/src/main/scala/monix/bio/IO.scala
> +  def suspend[A](fa: => Task[A]): Task[A] = {
Done

2020-11-08 08:19 UTC, WesselVS commented on core/shared/src/main/scala/monix/bio/internal/TaskTracing.scala
> +private[bio] object TaskTracing {
Done

2020-11-08 08:19 UTC, WesselVS commented on core/shared/src/main/scala/monix/bio/tracing/TaskEvent.scala
> +sealed abstract class TaskEvent
Done

2020-11-08 08:19 UTC, WesselVS commented on core/shared/src/main/scala/monix/bio/tracing/TaskTrace.scala
> +final case class TaskTrace(events: List[TaskEvent], captured: Int, omitted: Int) {
Done

2020-11-08 08:19 UTC, WesselVS commented on tracingTests/src/fulltracing/scala/tracing/FullStackTracingSuite.scala
> +object FullStackTracingSuite extends BaseTestSuite {
Done

2020-11-08 08:19 UTC, WesselVS commented on core/shared/src/main/scala/monix/bio/IO.scala
> +    }
Refactored

2020-11-10 21:37 UTC, Avasil approved these changes
Thank you once again!

Fantastic job, I will make it my priority to release it within a week or so :)

2020-11-10 21:37 UTC, merged